language:
 - cpp

compiler:
 - gcc
 - clang

os:
 - linux

install:
 - sudo apt-get update -qq
 - wget http://mirrors.kernel.org/ubuntu/pool/main/b/bison/bison_3.0.4.dfsg-1_amd64.deb
 - sudo dpkg -i bison_3.0.4.dfsg-1_amd64.deb
 - sudo apt-get install -qq cmake flex build-essential

before_script:
 - bin/project.sh

script:
 - cd build
 - make
 - make test

after_success:
 - echo "Success"

after_failure:
 - echo "Failure"

after_script:
 - echo "Script Finished."
