language:
 - cpp

compiler:
 - gcc
 - clang

os:
 - linux

install:
 - sudo apt-get update -qq
 - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
 - tar -xvzf bison-3.0.4.tar.gz
 - cd bison-3.0.4
 - ./configure --prefix=/usr/local/bison --with-libiconv-prefix=/usr/local/libiconv/
 - make
 - sudo make install
 - sudo apt-get install -qq cmake flex build-essential
 - cd -

before_script:
 - bin/project.sh

script:
 - cd build
 - make
 - make test

after_success:
 - echo "Success"

after_failure:
 - echo "Failure"

after_script:
 - echo "Script Finished."
